# Generated by Django 2.2.15 on 2020-08-06 05:40

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('pop', models.CharField(max_length=100)),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
    ]
